title: "Rolands Homeautomation"
description: "Smart-Home Projekte, ESPHome, Home Assistant und Automatisierungen."
baseurl: "" 
url: "https://github.com/schu-r/homeautomation"
markdown: kramdown
theme: minima      # optional, falls du Jekyll Theme willst
collections:
  projects:
    output: true


